config/routes.rb
Rails.application.routes.draw do
  resources :survey_responses, only: [:new, :create]

  resources :departments do
    get 'manage', on: :collection
  end

  # Need reservation/download as alias to show.ics for backwards compatability
  get '/reservations/download/:id', to: 'reservations#show', defaults: { format: 'ics' }

  # This not included below. because the index route shouldn't be nested
  resources :reservations, only: :index

  get '/sessions/download', to: 'sessions#download', as: :sessions_download
  get '/sessions/:id/reservations', to: 'sessions#reservations', as: :sessions_reservations
  get '/sessions/attendance/:id', to: redirect('/sessions/%{id}/reservations')
  post '/sessions/:id/email', to: 'sessions#email', as: :sessions_email

  resources :tags, :only => :show

  get '/topics/grid(/:year(/:month))', to: 'topics#grid', as: :grid
  get '/topics/upcoming', to: redirect('/'), as: :upcoming
  get '/topics/download/:id', to: 'topics#download', as: :download
  resources :topics, shallow: true do
    resources :sessions, except: :index do
      resources :reservations, except: [:index, :new] do
        member do
          get 'certificate'
          get 'send_reminder'
        end
      end
      member do
        get 'survey_results'
        get 'survey_comments/:which', to: 'sessions#survey_comments', which: /(most_useful|general)/
      end
    end
    member do
      get 'history'
      get 'survey_results'
      get 'survey_comments/:which', to: 'topics#survey_comments', which: /(most_useful|general)/
      get 'delete'
    end
    collection do
      get 'manage'
      get 'by-department'
      get 'by-site'
      get 'alpha'
    end
  end

  resources :users do
    collection do
      get 'autocomplete_search'
    end
  end

  get '/auth/:provider/callback', to: 'auth_sessions#create'
  get '/logout', to: 'auth_sessions#destroy', as: 'logout'

  root :to => 'topics#index'

  unless Rails.env.production?
    get '/test', to: 'test#index'
  end

end

app/models/topic.rb
require 'csv'

class Topic < ActiveRecord::Base
  belongs_to :department, touch: true
  has_many :sessions, -> { where(cancelled: false).includes([:topic, :occurrences, :site]).order('occurrences.time') }, :dependent => :destroy
  has_many :survey_responses, through: :sessions
  include SurveyAggregates
  has_many :documents, :dependent => :destroy
  accepts_nested_attributes_for :documents, :allow_destroy => true, :reject_if => :all_blank
  has_paper_trail
  acts_as_taggable

  scope :active, -> { where inactive: false }

  validates :name, :description, :department, presence: true
  validates :minutes, presence: true, numericality: { only_integer: true }
  validates_associated :department
  validates :survey_url, presence: { message: "must be specified to use an external survey." }, if: Proc.new{ |topic| topic.survey_type == SURVEY_EXTERNAL }
  validate :inactive_with_no_upcoming_sessions

  after_validation :delete_new_documents_on_error

  def inactive_with_no_upcoming_sessions
    errors[:base] << "You cannot delete a topic with upcoming sessions. Cancel the sessions first." if inactive? && upcoming_sessions.present?
  end

  SURVEY_NONE = 0
  SURVEY_INTERNAL = 1
  SURVEY_EXTERNAL = 2

  def self.upcoming
    # FIXME: ORDER BY doesn't work with GROUP BY. The caller will have to sort by whatever order 
    Topic.joins(sessions: :occurrences).merge(Occurrence.upcoming.order(:time)).group(:name)
  end

  def delete_new_documents_on_error
    if !self.errors.empty?
      # delete any documents that were just uploaded, since they will have to be uploaded again
      documents.destroy(documents.select(&:new_record?))
    end
    true
  end

  def deactivate!
    # if this is a brand new topic (no non-cancelled sessions), just go ahead and delete it
    if sessions.unscope(where: :cancelled).count == 0
      return self.destroy!
    end
    
    self.inactive = true
    self.save!
  end

  def <=>(other)
    self.name.downcase <=> other.name.downcase
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  # Work around issue where has_many through removes includes but keeps order
  def survey_responses
    super.reorder(nil).order('created_at DESC')
  end

  # Use this when you just care if there are any upcoming sessions, but don't need the details
  # If you do need the details at some point in the current request, use upcoming_sessions.length
  # or upcoming_sessions.present? if you don't need the exact count
  def upcoming_count
    @upcoming_count ||= @upcoming_sessions.try(:length) || Session.upcoming.where(topic: self).count
  end

  def upcoming_sessions
    @upcoming_sessions ||= sessions - past_sessions
  end

  def past_sessions
    @past_sessions ||= sessions.select { |s| s.in_past? }
  end

  def next_time
    upcoming_sessions.first.try(:time)
  end

  def sorted_tags
    #FIXME: can we have a default sort order?
    tags.sort { |a,b| a.name <=> b.name }
  end

  def self.to_csv(topics)
    CSV.generate do |csv|
      csv << Session::CSV_HEADER
      topics.each do |topic|
        topic.csv_rows.each { |row| csv << row }
      end
    end
  end

  def to_csv
    logger.debug { "in to_csv for #{name}" }
    CSV.generate do |csv|
      csv << Session::CSV_HEADER
      csv_rows.each { |row| csv << row }
    end
  end
  
  def csv_rows
    Rails.cache.fetch(["csv_rows", self]) do
      sessions.unscope(where: :cancelled).map { |session| session.csv_rows }.flatten(1)
    end
  end    

  def survey_responses_to_csv
    logger.debug { "in survey_responses_to_csv for #{name}" }
    CSV.generate do |csv|
      csv << Session::SURVEY_RESPONSES_CSV_HEADER
      survey_responses_csv_rows.each { |row| csv << row }
    end
  end
  
  def survey_responses_csv_rows(opts={})
    Rails.cache.fetch(["survey_responses_csv_rows", self, opts]) do
      s = sessions
      if opts[:start]
        s = s.merge(Occurrence.where("time >= ?", opts[:start].to_date))
      end
      if opts[:end]
        s = s.merge(Occurrence.where("time <= ?", opts[:end].to_date))
      end
      
      s.map { |session| session.survey_responses_csv_rows }.flatten(1)
    end
  end    

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  NO_AUTH_ACTIONS = [ :show, :download, :index, :alpha, :by_department, :by_site, :upcoming, :grid ]
  before_filter :authenticate, :except => NO_AUTH_ACTIONS
  before_action :set_topic, only: [:show, :new, :create, :edit, :download, :update, :delete, :destroy, :history, :survey_results, :survey_comments]
  before_action :set_title, only: [:show, :survey_results, :survey_comments]
  before_filter :ensure_authorized, except: NO_AUTH_ACTIONS + [:manage, :history]
  layout 'topic_collection', only: [:index, :by_department, :by_site, :alpha, :grid]

  def grid
    @cur_month = begin 
      Date.new(params[:year].to_i, params[:month].to_i) 
    rescue 
      Date.today.beginning_of_month 
    end
  end

  def show
    respond_to do |format|
      format.html
      format.atom
      format.ics do
        download
      end
      if authorized? @topic
        format.csv do
          data = cache(["#{date_slug}/topics/csv", @topic], expires_in: 1.day) do
            logger.debug { "generating csv for #{@topic.name}" }
            @topic.to_csv
          end
          send_csv data, @topic.to_param 
        end
      end
    end
  end

  def download
    data = cache(["#{date_slug}/topics/download", @topic], expires_in: 1.day) do
      calendar = RiCal.Calendar
      calendar.add_x_property 'X-WR-CALNAME', @topic.name
      @topic.upcoming_sessions.each do |session|
        session.to_event.each { |event| calendar.add_subcomponent( event ) }
      end
      calendar.export
    end
    send_data(data, :type => 'text/calendar')
  end
  
  # # GET /topics/new
  # def new
  #   @topic = Topic.new
  # end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        flash.now[ :alert ] = "There were problems updating this topic."
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.deactivate!
    respond_to do |format|
      format.html { redirect_to manage_topics_url, notice: "The topic \"#{@topic.name}\" has been deleted." }
      format.json { head :no_content }
    end
  end

  def manage
    redirect_to topics_path and return unless authorized?

    # sanitize the input to make sure we weren't passed anything bogus
    session[:topics] = case params['topics']
      when 'upcoming' then 'upcoming'
      else 'all'
    end if params.key?('topics')
    session[:departments] = case params['departments']
      when 'user' then 'user'
      else 'all'
    end if params.key?('departments')

    @upcoming = session[:topics] != 'all'
    @all_depts = current_user.admin? && (session[:departments] == 'all' || !current_user.editor?)

    # Editors: show topics for their departments only. 
    # Admins: show topics for their departments by default. Show all depts based on filter
    # Instructors: show departments for topics that they are instructors of
    @departments = Department.active.by_name
    list = @upcoming ? Topic.upcoming : Topic.active
    if !@all_depts
      @departments = @departments.where id: (
        current_user.department_ids + 
        current_user.sessions.map { |s| s.topic.department_id }
      ).uniq
      
      list = list.where(department: @departments)
    end

    @topics = Hash.new { |h,k| h[k] = SortedSet.new }
    list.each { |t| @topics[t.department_id] << t }

    render layout: 'application'
  end

  def history
    if authorized?(@topic) || current_user.instructor?(@topic)
      @page_title = "Topic History: " + @topic.name
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      if action_name == 'new' || action_name == 'create'
        @topic = Topic.new
      else
        @topic = Topic.find(params[:id])
      end
    end

    def set_title
      @page_title = @topic.try(:name) || 'Topic Not Found'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(
        :name, 
        :description,
        :tag_list,
        :department_id,
        :minutes, 
        :url, 
        :survey_type, 
        :survey_url,
        :certificate,
        documents_attributes: [:id, :item, :_destroy]
      )
    end

    def ensure_authorized
      redirect_to root_path unless authorized? @topic
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def session_info(session, opts={})
    print_date = !(opts[:print_date] == false) #default to true unless explicitly set to false    
    session_info = ""
    session_info << "#{session.topic.name} " if opts[:print_name] == true
    session_info << "#{formatted_time_range(session.time, session.topic.minutes, print_date)} ("
    session_info << " #{session.confirmed_count}"
    if session.seats
      session_info << " / #{session.seats}"
    end 
      session_info << " registered"
    if session.waiting_list_count > 0 
      session_info << ", #{session.waiting_list_count} waiting"
    end
    session_info << " )"
  end

  def link_to_session(session, opts={})
    link_to session_info(session, opts), session
  end
  
  def session_site(session)
    if session.site 
      s = '<span class="site">'
      s << session.site.name 
      s << '</span>'
      raw s
    end
  end

  def session_time_short(session)
    # strftime doesn't have the formats we want on OSX. We'll
    # have to do this the hard way
    time = session.time
    "#{time.month}/#{time.day}/#{time.strftime('%Y&nbsp;%l:%M%p')}".html_safe
  end

  def session_reservations_short(session)
    s = "#{session.confirmed_count}"
    s << " / #{session.seats}" if session.seats
    s
  end
  
  def session_list(sessions)
    list = sessions.map do |session| 
      "#{link_to_session(session)} #{session_site(session)}"
    end
    
    expandible_list list, visible: 12, allow_html: true
  end

  def link_to_document(d, opts = {})
    text = file_icon_image_tag(d.item.original_filename)
    text << ' ' << d.friendly_name
    link_to(text, asset_url(d.item.url), opts)
  end

  def file_icon_image_tag(filename, opts={})
    file_icon = FileIcon.new(filename)

    url = file_icon.icon_path
    
    opts = { :alt => t(:'file_icon.type', :type => (file_icon.type || filename)) }.merge opts
    image_tag(url, opts)
  end

  def grouped_by_date(topics)
    sessions = Hash.new { |h,k| h[k] = Array.new }
    topics.each do |topic|
      topic.upcoming_sessions.each do |session| 
        sessions[session.time.to_date] << session 
      end
    end
    
    sessions.keys.sort.each do |date| 
      yield date, sessions[date].sort_by(&:time)
    end if block_given?

    sessions
  end

  def grouped_by_department(topics)
    groups = Hash.new { |h,k| h[k] = Array.new }
    topics.each do |topic|
      groups[topic.department] << topic 
    end
    
    groups.keys.sort_by {|a| a.name.downcase }.each do |department| 
      yield department, groups[department].sort_by {|a| a.name.downcase }
    end if block_given?

    groups
  end

  def grouped_by_site(topics)
    sessions = Hash.new { |h,k| h[k] = Hash.new }
    topics.each do |topic|
      topic.upcoming_sessions.each do |session| 
        sessions[session.site][topic] = session if session.site && sessions[session.site][topic] == nil
      end
    end

    sessions.keys.sort.each do |site|
      yield site, sessions[site]
    end if block_given?

    sessions
  end

  def in_month(month)
    occurrences = Hash.new { |h,k| h[k] = Array.new }
    Occurrence.in_month(month).each do |occurrence|
      occurrences[occurrence.time.to_date] << occurrence
    end

    occurrences
  end

  def department_select(f)
    # for existing topics, only admins can modify dept
    # for new topics, limit selection to user's departments (for editors. Admins can select any dept).
    disabled = !(current_user.admin? || f.object.new_record?)
    departments = current_user.admin? ? Department.active.by_name : current_user.departments.by_name
    include_blank = f.object.new_record? && departments.size > 1
    f.association :department,
      label: 'Department:', 
      collection: departments, 
      value_method: :id, 
      label_method: :name, 
      :include_blank => include_blank, 
      :disabled => disabled
  end
end

app/views/topics/_details.html.erb
<div id="topic-details" class="content-section">
  <h2>Topic Details</h2>
  <dl>
    <% if local_assigns[:show_name] %>
    <dt>Topic:</dt>
    <dd><%= link_to topic.name, topic %></dd>
    <% end %>
    <dt>Description:</dt>
    <dd class="topic-description"><%= auto_link( simple_format( h( topic.description ) ) ) %></dd>
    <% if !topic.tags.blank? %>
      <dt>Tags:</dt>
      <dd><%= topic.sorted_tags.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></dd>
    <% end %>
    <dt>Duration:</dt>
    <dd><%=h topic.minutes %> minutes</dd>
    <dt>Department:</dt>
    <dd><%=link_to topic.department.name, topic.department %></dd>
    <% if !topic.url.blank? %>
      <dt>Additional Info:</dt>
      <dd><%= link_to topic.url, topic.url %></dd>
    <% end %>
    <% if !topic.documents.blank? %>
      <dt>Workshop Materials:</dt>
      <% topic.documents.each do |document| %>
        <dd><%= link_to_document(document) %></dd>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/topics/_document_fields.html.erb
<div class='nested-fields'>
  <% if !f.object.new_record? %>
    <%= link_to_document f.object, :class => 'document' %>
  <% else %>
    <%= f.file_field :item %>
  <% end %>
  <%= link_to_remove_association "remove", f %>
</div>

app/views/topics/_form.html.erb
<%= simple_form_for(@topic, data: {prevent_double_submit: ''}) do |f| %>
  <%= model_error_messages @topic %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Topic Name:' %>
    <%= f.input :description, label: 'Description of Topic:' %>
    <%= f.input :tag_list, input_html: {value: @topic.tag_list.to_s}, label:'Tags:' %>
    <%= department_select(f) %>
    <%= f.input :minutes, label: 'Class time in Minutes:' %>
    <%= f.input :url, label: 'URL with More Information on Class:' %>
    <%= f.input :survey_type, label: 'Post-Class Survey:',
      as: :radio_buttons, 
      collection: [
        ['None', Topic::SURVEY_NONE], 
        ['Automatic', Topic::SURVEY_INTERNAL], 
        ['External', Topic::SURVEY_EXTERNAL]
      ] %>
    <%= f.input :survey_url, label: 'External Survey URL:' %>
    <%= f.input :certificate, label: 'Certificate of Completion:',
      as: :radio_buttons %>
    <div class="documents">
      <%= f.label 'Workshop Materials:' %>
      <%= f.simple_fields_for :documents do |document| %>
        <%= render 'document_fields', :f => document %>
      <% end %>
      <div class='add-fields'>
        <%= link_to_add_association 'upload new material', f, :documents %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Cancel', (@topic.new_record? ? topics_path : @topic) %>
  </div>
<% end %>

app/views/topics/alpha.html.erb
<% cache("#{sess_key}/#{date_slug}/#{sites_key}/topics/alpha", expires_in: 1.day)  do %>
  <% @topics = Topic.upcoming %>
  <% if @topics.blank? %>
    <div class="empty-list">
      <p>Sorry, there are no upcoming sessions at this time. Please check again later!</p>
    </div>
  <% else %>
    <ul class="topic-list">
      <% @topics.sort_by {|a| a.name.downcase }.each do |topic| %>
        <% cache(["#{date_slug}/#{sites_key}/topics/alpha", topic], expires_in: 1.day) do %>
          <li>
            <%= link_to topic.name, topic %>
            <% if topic.upcoming_sessions.present? %>
              <% session = topic.upcoming_sessions[0] %>
              <div class="session-info">
                <span class="session-link"><%= link_to_session session %></span>
                <%= session_site(session) %>
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/topics/by_department.html.erb
<% cache("#{sess_key}/#{date_slug}/#{sites_key}/topics/by_department", expires_in: 1.day)  do %>
  <% @topics = Topic.upcoming.includes(:department) %>
  <% if @topics.blank? %>
    <div class="empty-list">
      <p>Sorry, there are no upcoming sessions at this time. Please check again later!</p>
    </div>
  <% else %>
    <% grouped_by_department(@topics) do |department, topics| %>
      <div class="content-section">
        <h2><%= department.name %></h2>
        <ul class="topic-list">
          <% topics.each do |topic| %>
            <% cache(["#{date_slug}/#{sites_key}/topics/by_department", topic], expires_in: 1.day) do %>
              <li>
                <%= link_to topic.name, topic %>
                <% if topic.upcoming_sessions.present? %>       
                <% session = topic.upcoming_sessions[0] %>
                <div class="session-info">
                  <span class="session-link"><%= link_to_session session %></span>
                  <%= session_site(session) %>
                </div>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/topics/by_site.html.erb
<% cache("#{sess_key}/#{date_slug}/#{sites_key}/topics/by_site", expires_in: 1.day) do %>
  <% @topics = Topic.upcoming.includes(:sessions) %>
  <% if @topics.blank? %>
    <div class="empty-list">
      <p>Sorry, there are no upcoming sessions at this time. Please check again later!</p>
    </div>
  <% else %>
    <% grouped_by_site(@topics) do |site, sessions| %>
      <div class="content-section">
        <h2><%= site.name %></h2>
        <ul class="topic-list">
          <% sessions.keys.sort_by {|a| a.name.downcase }.each do |topic| %>
            <% cache(["#{date_slug}/topics/by_site", topic], expires_in: 1.day) do %>
              <li>
                <%= link_to topic.name, topic %>
                <div class="session-info">
                  <span class="session-link"><%= link_to_session sessions[topic] %></span>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/topics/delete.html.erb
<div id="delete-topic" class="content-section">
  <h2>Delete Topic?</h2>
  <p class="confirmation">Are you sure you want to delete this topic?</p>

  <p>This topic has been held <%= pluralize(@topic.past_sessions.size, 'time') %>.</p>
  
  <%= link_to "Delete This Topic", @topic, 
        method: :delete,
        data: { confirm: "Are you sure you want to delete this topic?" }, 
        class: 'delete-button register-button' 
  %>
  
  <%= link_to "Cancel", @topic, :class => "register-button" %>
  
</div>

<div id="past-session-details" class="session-list content-section">
  <% if authorized?(@topic) && @topic.past_sessions.present? %>
    <h2>Past Sessions</h2>
    <%= session_list(@topic.past_sessions.reverse) %>
  <% end %>
</div>

app/views/topics/grid.html.erb
<% content_for :head do %>
  <meta name="robots" content="noindex, nofollow">
<% end %>

<% cache("#{sess_key}/topics/grid/#{date_slug(@cur_month)}", expires_in: 1.day)  do %>
  <table id="topic-grid">
    <caption>
      <%= link_to "◄", "/topics/grid/#{@cur_month.prev_month.year}/#{@cur_month.prev_month.month}" %>
      <%= @cur_month.strftime('%B %Y') %>
      <%= link_to "►", "/topics/grid/#{@cur_month.next_month.year}/#{@cur_month.next_month.month}" %>
    </caption>
    <thead>
      <tr>
        <% (0...7).each do |day| %>
          <th><%=t(:'date.day_names')[day] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @occurrences = in_month(@cur_month) %>
      <% full_month(@cur_month).in_groups_of(7).each do |week| %>
        <tr>
          <% week.each do |day| %>
            <td class="<%= date_class(day, @cur_month) %>">
              <div class="day">
                <%= day.day %>
              </div>
              <div class="grid-cell-topic-list">
                <% if @occurrences.has_key? day %>
                  <% reset_cycle %>
                  <% @occurrences[day].each do |occurrence| %>
                    <% cache(["topics/grid/#{date_slug(day)}", occurrence.session.topic, occurrence.session, occurrence]) do %>
                      <div class="session <%= cycle("odd", "even") -%>">
                        <%= link_to occurrence.session.topic.name, occurrence.session, :title => occurrence.session.topic.name %>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/topics/history.html.erb
<div id="manage-topics">
  
  <% if @topic.sessions.blank? %>
    <div class="content-section">
      <h2>No sessions found</h2>
      <div class="empty-list">
        <p>There are no sessions to display.</p>
      </div>
    </div>
  <% else %>
  
  <div class="content-section">
    <h2><%= @topic.name %>
        <%= link_to("Subscribe to the XML feed for this topic",
          topic_path(@topic, :format => :atom), :class => 'feed-link') %>
    </h2>
    <div class="action-list">
      <% if authorized? @topic %>
        <p class="download-link download-csv">
          <%= link_to "Download Attendance History", topic_path(@topic, :format => :csv ) %>
        </p>
      <% end %>
    </div>
    <table class="topic-list">
      <thead>
        <tr>
          <th scope="col" class="topic-name">Session</th>
          <th scope="col" class="topic-site"><%=t :'activerecord.attributes.session.site' %></th> 
          <th scope="col" class="topic-instructors">Instructor(s)</th> 
          <th scope="col" class="topic-count">Reservations</th>
        </tr>
      </thead>
      <tbody>
        <% @topic.sessions.each do |session| %>
          <% authorized = authorized? session %>
          <% cache(["#{sites_key}/topics/history", session, "#{authorized ? '' : 'not-'}authorized"]) do %>
            <tr class="<%= cycle("even", "odd") %>">
            <td class="topic-name">
              <%= link_to formatted_time_range(session.time, @topic.minutes), session, :class => 'date' %>
            </td>
            <td class="topic-site">
              <%= session.site.name %>
            </td>
            <td class="topic-instructors">
              <%= session.instructors.map do |user|
                    link_to user.name, user_path(user)
                  end.join(', ').html_safe 
              %>
            </td>
            <td class="topic-count">
              <% if authorized %>
                <%= link_to session_reservations_short(session), 
                  session_reservations_path( session ) %>
              <% else %>
                <%= session_reservations_short(session) %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <% end %>
</div>

app/views/topics/index.html.erb
<% cache("#{sess_key}/#{date_slug}/#{sites_key}/topics/by-date", expires_in: 1.day)  do %>
  <% @topics = Topic.upcoming.includes(:sessions) %>
  <% if @topics.blank? %>
    <div class="empty-list">
      <p>Sorry, there are no upcoming sessions at this time. Please check again later!</p>
    </div>
  <% else %>
    <% grouped_by_date(@topics) do |date, sessions| %>
      <div class="content-section">
        <h2><%= date.strftime('%A, %B %e, %Y') %></h2>
        <ul class="topic-list">
          <% sessions.each do |session| %>
            <% cache(["#{sites_key}/topics/by-date", session.topic, session]) do %>
              <li>
                <%= link_to session.topic.name, session.topic %>
                <div class="session-info">
                  <span class="session-link"><%= link_to_session session, :print_date => false %></span>
                  <%= session_site(session) %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/show.html.erb
<% content_for :head do %>
  <% if @topic.inactive? %>
    <meta name="robots" content="noindex">
  <% end %>
<% end %>

<div id="session-details" class="session-list content-section">
  <h2>Upcoming Sessions
    <%= link_to( 
        "Subscribe to the XML feed for this topic",
         topic_path(@topic, :format => :atom),
         :class => 'feed-link') %>
  </h2>
  <% if @topic.upcoming_sessions.present? %>
    <%= session_list(@topic.upcoming_sessions) %>
  <% else %>
    There are no sessions scheduled at this time.
  <% end %>
</div>

<%= render partial: "topics/details", 
            locals: {topic: @topic} %>

<div id="past-session-details" class="session-list content-section">
<% if authorized?(@topic) && @topic.past_sessions.present? %>
  <h2>Past Sessions</h2>
  <%= session_list(@topic.past_sessions.reverse) %>
<% end %>
</div>

app/views/topics/survey_comments.html.erb
<%= render  "survey_responses/comments", :model_object => @topic, :which => params[:which] %>

app/views/topics/survey_results.html.erb
<%= render  "survey_responses/survey_summary", :model_object => @topic %>