config/routes.rb
Rails.application.routes.draw do
  resources :survey_responses, only: [:new, :create]

  resources :departments do
    get 'manage', on: :collection
  end

  # Need reservation/download as alias to show.ics for backwards compatability
  get '/reservations/download/:id', to: 'reservations#show', defaults: { format: 'ics' }

  # This not included below. because the index route shouldn't be nested
  resources :reservations, only: :index

  get '/sessions/download', to: 'sessions#download', as: :sessions_download
  get '/sessions/:id/reservations', to: 'sessions#reservations', as: :sessions_reservations
  get '/sessions/attendance/:id', to: redirect('/sessions/%{id}/reservations')
  post '/sessions/:id/email', to: 'sessions#email', as: :sessions_email

  resources :tags, :only => :show

  get '/topics/grid(/:year(/:month))', to: 'topics#grid', as: :grid
  get '/topics/upcoming', to: redirect('/'), as: :upcoming
  get '/topics/download/:id', to: 'topics#download', as: :download
  resources :topics, shallow: true do
    resources :sessions, except: :index do
      resources :reservations, except: [:index, :new] do
        member do
          get 'certificate'
          get 'send_reminder'
        end
      end
      member do
        get 'survey_results'
        get 'survey_comments/:which', to: 'sessions#survey_comments', which: /(most_useful|general)/
      end
    end
    member do
      get 'history'
      get 'survey_results'
      get 'survey_comments/:which', to: 'topics#survey_comments', which: /(most_useful|general)/
      get 'delete'
    end
    collection do
      get 'manage'
      get 'by-department'
      get 'by-site'
      get 'alpha'
    end
  end

  resources :users do
    collection do
      get 'autocomplete_search'
    end
  end

  get '/auth/:provider/callback', to: 'auth_sessions#create'
  get '/logout', to: 'auth_sessions#destroy', as: 'logout'

  root :to => 'topics#index'

  unless Rails.env.production?
    get '/test', to: 'test#index'
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :topics, -> { where inactive: false }
  has_many :permissions
  has_many :users, :through => :permissions
  accepts_nested_attributes_for :permissions, :reject_if => lambda { |p| p['name_and_login'].blank? }, :allow_destroy => true
  has_paper_trail

  scope :active, -> { where inactive: false }
  scope :by_name, -> { order :name }

  validates :name, presence: true
  validate :inactive_with_no_active_topics
  after_validation Proc.new { |d| d.name = d.name_was if d.name.blank? }, on: :update
  
  def inactive_with_no_active_topics
    errors[:base] << 'You cannot delete a department with active topics. Delete the topics first.' if inactive? && topics.present?
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def upcoming
    topics.upcoming
  end

  def deactivate!
    # if this is a brand new department (no topics, active or inactive), just go ahead and delete it
    if topics.unscope(where: :inactive).count == 0
      return self.destroy
    end
    
    self.inactive = true
    self.save
  end

  def to_csv
    CSV.generate do |csv|
      csv << Session::CSV_HEADER
      csv_rows.each { |row| csv << row }
    end
  end

  def csv_rows
    topics.map { |topic| topic.csv_rows }.flatten(1)
  end

  def survey_responses_to_csv(opts={})
    CSV.generate do |csv|
      csv << Session::SURVEY_RESPONSES_CSV_HEADER
      survey_responses_csv_rows(opts).each { |row| csv << row }
    end
  end

  def survey_responses_csv_rows(opts={})
    topics.map { |topic| topic.survey_responses_csv_rows(opts) }.flatten(1)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate, :except => [ :show, :index ]
  before_action :set_department, only: [:new, :show, :create, :edit, :update, :destroy]
  before_filter :ensure_authorized, except: [:index, :show, :manage]

  # GET /departments/1
  # GET /departments/1.json
  def show
    @page_title = @department.name
    respond_to do |format|
      format.html
      format.atom
      if authorized?(@department) || (current_user && current_user.editor?(@department))
        format.csv do
          data = cache(['departments/csv', @department]) do
            logger.debug { "Generating csv for department #{@department.name}" }
            @department.to_csv
          end
          send_csv data, @department 
        end
      end
    end
  end

  # POST /departments
  # POST /departments.json
  def create
    respond_to do |format|
      if @department.save
        format.html { redirect_to manage_departments_path, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to manage_departments_path, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        flash.now[:alert] = 'There were problems updating this department.' 
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.deactivate!
    respond_to do |format|
      format.html { redirect_to manage_departments_path, notice: "The department \"#{@department.name}\" has been deleted." }
      format.json { head :no_content }
    end
  end

  def manage
    @departments = Department.active.by_name    
    redirect_to departments_path unless authorized? @departments
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      if action_name == 'new'
        @department = Department.new
      elsif action_name == 'create'
        @department = Department.new(department_params)
      else
        @department = Department.find(params[:id])
      end
      @department.permissions.build unless @department.permissions.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, 
        permissions_attributes: [:id, :name_and_login, :_destroy]
      )
    end

    def ensure_authorized
      redirect_to departments_path unless authorized? @department
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= simple_form_for(@department, data: {prevent_double_submit: ''}) do |f| %>
  <%= model_error_messages @department %>
  
  <div class="form-inputs">
    <%= f.input :name, label: 'Department Name:' %>
    
    <div id="permissions">
      <%= f.label :permissions, "Users:", class: 'field-label' %>
      <%= f.simple_fields_for :permissions do |permission| %>
        <%= render "permission_fields", :f => permission %>
      <% end %>
      <div class='add-fields'>
        <%= link_to_add_association 'add another user', 
          f, :permissions %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Cancel', manage_departments_path %>
  </div>
<% end %>

<div id="user-modal" class="content-section" style="display:none;">
  <h2>Add New User</h2>
  <%= render 'users/form', user: User.new, modal: true %>
</div>

app/views/departments/_permission_fields.html.erb
<div class="nested-fields">
  <div class="input string foo">
    <%= f.input :name_and_login, 
      url: autocomplete_search_users_path, 
      as: :autocomplete,
      label: false, 
      wrapper: false
    %>
    <%= link_to_remove_association "remove", f %>
  </div>
</div>

app/views/departments/edit.html.erb
<% content_for :admin_tools do %>
  <% if @department && authorized?(@department) && !@department.new_record? && @department.topics.blank? %>
    <p>
      <%= link_to "Delete This Department", @department, method: :delete, 
      data: { confirm: "Are you sure you want to delete this department?" } %>
    </p>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/departments/index.html.erb
<% cache("#{sess_key}/departments/index") do %> 
  <ul id="department-list">
    <% Department.active.by_name.each do |department| %>
      <li>
        <%= link_to department.name, department %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/departments/manage.html.erb
<% content_for :admin_tools do %>
  <% if current_user.admin? %>
    <p>
      <%= link_to "Create New Department", new_department_path %>
    </p>
  <% end %>
<% end %>

<div id="manage-departments">
  <div class="content-section">
    <h2>Department List</h2>
    <ul id="department-list">
      <% @departments.each do |department| %>
        <li class="<%= cycle("even", "odd") %>">
          <%= link_to department.name, edit_department_path(department) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/departments/new.html.erb
<%= render 'form' %>

app/views/departments/show.html.erb
<% content_for :head do %>
  <% if @department.inactive? %>
    <meta name="robots" content="noindex">
  <% end %>
<% end %>

<% cache(["#{sess_key}/#{date_slug}/#{sites_key}/departments/show/upcoming", @department], expires_in: 1.day)  do %>
  <% if @department.topics.present? %>
    <div class="content-section">
      <h2>Upcoming sessions
        <%= link_to( 
          "Subscribe to the XML feed for this department",
           department_path(@department, :format => :atom),
           :class => 'feed-link') %>
      </h2>
      <% topics = @department.upcoming %>
      <% if topics.present? %>
        <ul class="topic-list">
          <% topics.sort_by(&:next_time).each do |topic| %>
            <% cache(["#{date_slug}/#{sites_key}/departments/show/upcoming", topic], expires_in: 1.day) do %>
              <li>
                <%= link_to topic.name, topic %>
                <% if topic.upcoming_sessions.present? %>       
                  <% session = topic.upcoming_sessions.first %>
                  <div class="session-info">
                    <span class="session-link"><%= link_to_session session %></span>
                    <%= session_site(session) %>
                  </div>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      <% else %>
        <div>This department does not currently have any upcoming sessions.</div>
      <% end %>
    </div>

    <% cache(["departments/show/all", @department]) do %>
      <div class="content-section">
        <h2>All topics offered by this department</h2>
        <ul class="topic-list">
          <% @department.topics.sort.each do |topic| %>
            <% cache(["departments/show/all", topic]) do %>
              <li>
                <%= link_to topic.name, topic %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% else %>
    <div class="empty-list">This department does not currently have any topics available.</div>
  <% end %>
<% end %>