config/routes.rb
Rails.application.routes.draw do
  resources :survey_responses, only: [:new, :create]

  resources :departments do
    get 'manage', on: :collection
  end

  # Need reservation/download as alias to show.ics for backwards compatability
  get '/reservations/download/:id', to: 'reservations#show', defaults: { format: 'ics' }

  # This not included below. because the index route shouldn't be nested
  resources :reservations, only: :index

  get '/sessions/download', to: 'sessions#download', as: :sessions_download
  get '/sessions/:id/reservations', to: 'sessions#reservations', as: :sessions_reservations
  get '/sessions/attendance/:id', to: redirect('/sessions/%{id}/reservations')
  post '/sessions/:id/email', to: 'sessions#email', as: :sessions_email

  resources :tags, :only => :show

  get '/topics/grid(/:year(/:month))', to: 'topics#grid', as: :grid
  get '/topics/upcoming', to: redirect('/'), as: :upcoming
  get '/topics/download/:id', to: 'topics#download', as: :download
  resources :topics, shallow: true do
    resources :sessions, except: :index do
      resources :reservations, except: [:index, :new] do
        member do
          get 'certificate'
          get 'send_reminder'
        end
      end
      member do
        get 'survey_results'
        get 'survey_comments/:which', to: 'sessions#survey_comments', which: /(most_useful|general)/
      end
    end
    member do
      get 'history'
      get 'survey_results'
      get 'survey_comments/:which', to: 'topics#survey_comments', which: /(most_useful|general)/
      get 'delete'
    end
    collection do
      get 'manage'
      get 'by-department'
      get 'by-site'
      get 'alpha'
    end
  end

  resources :users do
    collection do
      get 'autocomplete_search'
    end
  end

  get '/auth/:provider/callback', to: 'auth_sessions#create'
  get '/logout', to: 'auth_sessions#destroy', as: 'logout'

  root :to => 'topics#index'

  unless Rails.env.production?
    get '/test', to: 'test#index'
  end

end

app/views/layouts/_analytics.erb
<% if Rails.application.secrets.google_analytics_tracking_id.present? %>
  <%#
    google_analytics_tracking_id should be defined in config/secrets.yml
    It will be something like 'UA-12345678-1'.
    Create an account at https://www.google.com/analytics
    NB: If this page is cached, you will have to manually expire it when
    you set or change the google_analytics_tracking_id value.
  %>
  <script>

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= Rails.application.secrets.google_analytics_tracking_id %>', 'auto');
    ga('send', 'pageview');

  </script>

<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_search.html.erb
<form id="search-form" accept-charset="UTF-8" action="https://www.txstate.edu/search/">
  <div class="text-search">
    <label for="q">Search topics</label>
    <input type="text" name="query" id="q" size="15" value="" />
    <input id="webtools-search-form-sitesearch" type="hidden" name="sitesearch" value="signup.txstate.edu" />
    <input class="submit" type="submit" value="Go">
  </div>  
</form>

app/views/layouts/_topbanner.html.erb
<%- if (File.exists?("#{Rails.root}/app/assets/images/logo.jpg")) -%>
  <%= link_to image_tag('logo.jpg', alt: t(:logo_alt)), logo_link_url, title: t(:logo_title), class: 'topbanner-homelink' %>
<%- end -%>

<a class="topbanner-sitename" href="<%= root_path %>"><%=t :site_name %></a>

<%- if (File.exists?("#{Rails.root}/app/views/layouts/_search.html.erb")) -%>
  <%= render 'layouts/search' %>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
    <%= page_title %>
    <%=t :site_title, default: '' %>
  </title>
  <link href="<%= asset_path 'favicon.png' %>" type="image/x-icon" rel="shortcut icon">
  <%- if (File.exists?("#{Rails.root}/app/assets/stylesheets/application.css")) -%>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  <%- end -%>
  <%- if (File.exists?("#{Rails.root}/app/assets/javascripts/application.js")) -%>
    <%= javascript_include_tag 'application' %>
  <%- end -%>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,user-scalable=yes">
  <%= render 'layouts/analytics' %>
</head>
<body>
  <div class="topbanner">
    <div class="topbanner-shadow"></div>
    <div class="topbanner-content">
      <%= render 'layouts/topbanner' %>
    </div>
  </div>

  <div id="container">
    <div class="left-column">
      <div class="navigation">
        <p>
          <% if current_user -%>
            <%=h current_user.name %> <span class="logout-link" data-no-turbolink>(<%= link_to("log out", '/logout') %>)</span>
          <% elsif false %>
          <% elsif auth_user -%>
            <%=h auth_user %> <span class="logout-link" data-no-turbolink>(<%= link_to("log out", '/logout') %>)</span>
          <% end -%>
        </p>
        <p><%= link_to "Your Reservations", reservations_path %></p>
        <p><%= link_to "Available Topics", topics_path, :id => 'topic-list-link' %></p>
        <p><%= link_to "Department List", departments_path %></p>
      </div>
      <div class="sidebar">
        <%= yield :sidebar %>
      </div>
      <% if authorized? %>
        <div class="admin-tools">
          <h1>ADMIN TOOLS</h1>
          <%= yield :admin_tools %>
          <p><%= link_to "Manage Topics", manage_topics_path %></p>
          <% if current_user.admin? %>
            <p><%= link_to "Manage Departments", manage_departments_path %></p>
            <p><%= link_to "Manage Users", users_path %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div id="right-column">
      <% unless flash[ :notice ].blank? %>
        <div id="notification"><%=h flash[ :notice ] %></div>
      <% end %>
      <% unless flash[ :alert ].blank? %>
        <div id="error"><%=h flash[ :alert ] %></div>
      <% end %>
      <div id="contents">
        <% unless @no_title %>
          <h1><%= image_tag(@title_image, :class=>"title-image") if @title_image %>
          <%= page_title %></h1>
        <% end %>
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </div>
      <div id="footer">
        <%=t(:'footer_text_html') %>
      </div>
  </div>

</body>
</html>

app/views/layouts/sessions.html.erb
<% content_for :admin_tools do %>
  <% if @session && authorized?(@session) && !@session.new_record? %>
    <p><%= link_to "View Session Details", @session %>
    <p><%= link_to "View Reservations", sessions_reservations_path( @session ) %>
    <%- if @session.in_past? -%>
      <p><%= link_to "View Survey Results", survey_results_session_path( @session ) %>
    <%- end -%>
    <% if @session.in_future? && !@session.cancelled %>
      <p><%= link_to "Update Session Details", edit_session_path %>
      <p><%= link_to "Cancel Session", '#', :id => 'cancel-session-link' %>
    <% end %>
  <% end %>
  <% if @session && authorized?(@session.topic) %>
    <p><%= link_to "Create New Session", new_topic_session_path( @session.topic ) %></p>
  <% end %>
<% end %>

<% content_for :content do %>

  <%= yield %>

  <% if @session.in_future? && !@session.cancelled %>
    <%= render :partial => "cancel", :locals => { :session => @session }%>
  <% end %>

<% end %>

<%= render :file => 'layouts/application' %>

app/views/layouts/static.html.erb
<% content_for :content do %>
  <!--
    This file was automatically generated on <%= Time.zone.now %>.
    Original file is at <%= __FILE__ %>
    run `rake static:generate` to rebuild
  -->

  <%= yield %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/topic_collection.html.erb
<% content_for :sidebar do %>
  <div class="download-link download-calendar">
    <%= link_to "[add all topics to calendar]", :protocol => "webcal", :controller => 'sessions', :host => request.host, :port => request.port, :action => 'download' %>
  </div>
<% end %>
   
<% content_for :content do %>
  <div id="topic-list-nav">
    <%= link_to 'group by date', '/topics' %>
    <%= link_to 'group by department', '/topics/by-department' %>
    <%= link_to t(:'topics.index.by_site'), '/topics/by-site' %>
    <%= link_to 'alphabetical list', '/topics/alpha' %>
    <%= link_to 'month at a glance', '/topics/grid' %>
  </div>

  <%= yield %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/topics.html.erb
<% content_for :admin_tools do %>
  <% if @topic && !@topic.new_record? %>
    <p><%= link_to "View Topic History", history_topic_path( @topic ) %>
    <p><%= link_to "View Topic Details", @topic %>
    <% if authorized? @topic %>
      <p><%= link_to "View Survey Results", survey_results_topic_path( @topic ) %>
      <% unless @topic.inactive? %>
        <p><%= link_to "Update Topic Details", edit_topic_path( @topic ) %></p>
        <% if @topic.upcoming_count.zero? %>
          <p><%= link_to "Delete Topic", delete_topic_path( @topic ) %></p>
        <% end %>
          <p><%= link_to "Create New Session", new_topic_session_path( @topic ) %></p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <% if @topic && !@topic.new_record? %>
    <div class="download-link download-calendar">
      <%= link_to "[add all sessions to calendar]", download_url(@topic, :protocol => "webcal") %>
    </div>
  <% end %>
<% end %>

<% content_for :content do %>
  <%#= error_messages_for 'topic' %>
  <% if @topic && @topic.inactive? %>
    <div class="inactive-topic-message">
      This topic is no longer active. No further sessions will be held.
    </div>
  <% end %> 
  <%= yield %>
<% end %>

<%= render :file => 'layouts/application' %>